fixtures:
  repositories:
    'nisclient':
      repo:      'https://github.com/Ericsson/puppet-module-nisclient.git'
      ref:       'v2.0.0'
    'nsswitch':
      repo:      'https://github.com/kodguru/puppet-nsswitch.git'
      ref:       'v3.1.0-forked'
    'pam':
      repo:      'https://github.com/kodguru/puppet-module-pam.git'
      ref:       'v3.9.0'
    'rpcbind':
      repo:      'https://github.com/ghoneycutt/puppet-module-rpcbind.git'
      ref:       'v3.0.0'
    'stdlib':
      repo:      'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:       'v8.2.0'
  symlinks:
    vas: "#{source_dir}"
