fixtures:
  repositories:
    'common':    'https://github.com/ghoneycutt/puppet-module-common.git'
    'pam':       'https://github.com/ghoneycutt/puppet-module-pam.git'
    'nsswitch':  'https://github.com/ghoneycutt/puppet-module-nsswitch.git'
    'nisclient': 'https://github.com/Ericsson/puppet-module-nisclient.git'
    'rpcbind':   'https://github.com/ghoneycutt/puppet-module-rpcbind.git'
    'stdlib':
      repo:      'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:       '4.10.0'
  symlinks:
    vas: "#{source_dir}"
