name 'ericsson-vas'
version '0.8.0'
source 'https://github.com/Ericsson/puppet-module-vas.git'
author 'ericsson'
license 'Apache License, Version 2.0'
summary 'Manage VAS - Quest Authentication Services'
description 'Manage VAS - Quest Authentication Services'
project_page 'https://github.com/Ericsson/puppet-module-vas'

dependency 'ericsson/nisclient',  '>= 0.1.0'
dependency 'ghoneycutt/pam',      '>= 2.0.0'
dependency 'ghoneycutt/nsswitch', '>= 1.0.0'
dependency 'puppetlabs/stdlib',   '>= 3.2.0'
