name: Run PDK tests on Puppet 7.x

on:
  - push
  - pull_request

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - name: Run unit tests
      # Modified puppets-epic-show-theatre with gcc and make installed
      uses: kodguru/action-pdk-test-unit@buildtools
      with:
        puppet-version: "7"
