name: Run PDK tests on Puppet 7.x

on:
  - push
  - pull_request

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: Run unit tests
      # Modified puppets-epic-show-theatre with gcc and make installed
      uses: ericsson/action-pdk-test-unit@buildtools
      with:
        puppet-version: "7"
