---
name: Run PDK validate

on:
  - push
  - pull_request

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run pdk validate
      # Modified puppets-epic-show-theatre with gcc and make installed
      uses: ericsson/action-pdk-validate@buildtools
